# About The Dataset

The original source of the data is Australian Government's Bureau of Meteorology and the latest data can be gathered from [http://www.bom.gov.au/climate/dwo/](http://www.bom.gov.au/climate/dwo/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01).

The dataset to be used has extra columns like 'RainToday' and our target is 'RainTomorrow', which was gathered from the Rattle at [https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData](https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)


This dataset contains observations of weather metrics for each day from 2008 to 2017. The **weatherAUS.csv** dataset includes the following fields:

| Field         | Description                                           | Unit            | Type   |
| ------------- | ----------------------------------------------------- | --------------- | ------ |
| Date          | Date of the Observation in YYYY-MM-DD                 | Date            | object |
| Location      | Location of the Observation                           | Location        | object |
| MinTemp       | Minimum temperature                                   | Celsius         | float  |
| MaxTemp       | Maximum temperature                                   | Celsius         | float  |
| Rainfall      | Amount of rainfall                                    | Millimeters     | float  |
| Evaporation   | Amount of evaporation                                 | Millimeters     | float  |
| Sunshine      | Amount of bright sunshine                             | hours           | float  |
| WindGustDir   | Direction of the strongest gust                       | Compass Points  | object |
| WindGustSpeed | Speed of the strongest gust                           | Kilometers/Hour | object |
| WindDir9am    | Wind direction averaged of 10 minutes prior to 9am    | Compass Points  | object |
| WindDir3pm    | Wind direction averaged of 10 minutes prior to 3pm    | Compass Points  | object |
| WindSpeed9am  | Wind speed averaged of 10 minutes prior to 9am        | Kilometers/Hour | float  |
| WindSpeed3pm  | Wind speed averaged of 10 minutes prior to 3pm        | Kilometers/Hour | float  |
| Humidity9am   | Humidity at 9am                                       | Percent         | float  |
| Humidity3pm   | Humidity at 3pm                                       | Percent         | float  |
| Pressure9am   | Atmospheric pressure reduced to mean sea level at 9am | Hectopascal     | float  |
| Pressure3pm   | Atmospheric pressure reduced to mean sea level at 3pm | Hectopascal     | float  |
| Cloud9am      | Fraction of the sky obscured by cloud at 9am          | Eights          | float  |
| Cloud3pm      | Fraction of the sky obscured by cloud at 3pm          | Eights          | float  |
| Temp9am       | Temperature at 9am                                    | Celsius         | float  |
| Temp3pm       | Temperature at 3pm                                    | Celsius         | float  |
| RainToday     | If there was rain today                               | Yes/No          | object |
| RainTomorrow  | If there is rain tomorrow                             | Yes/No          | float  |

Column definitions were gathered from [http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml](http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)

In [58]:
#Import all the necessary libraries
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


In [3]:
df=pd.read_csv('Weather_Data.csv')

In [4]:
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

In [12]:
df.shape

(3271, 22)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3271 entries, 0 to 3270
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           3271 non-null   object 
 1   MinTemp        3271 non-null   float64
 2   MaxTemp        3271 non-null   float64
 3   Rainfall       3271 non-null   float64
 4   Evaporation    3271 non-null   float64
 5   Sunshine       3271 non-null   float64
 6   WindGustDir    3271 non-null   object 
 7   WindGustSpeed  3271 non-null   int64  
 8   WindDir9am     3271 non-null   object 
 9   WindDir3pm     3271 non-null   object 
 10  WindSpeed9am   3271 non-null   int64  
 11  WindSpeed3pm   3271 non-null   int64  
 12  Humidity9am    3271 non-null   int64  
 13  Humidity3pm    3271 non-null   int64  
 14  Pressure9am    3271 non-null   float64
 15  Pressure3pm    3271 non-null   float64
 16  Cloud9am       3271 non-null   int64  
 17  Cloud3pm       3271 non-null   int64  
 18  Temp9am 

In [15]:
df.describe().T

count         mean        std    min      25%     50%     75%  \
MinTemp        3271.0    14.877102   4.554710    4.3    11.00    14.9    18.8   
MaxTemp        3271.0    23.005564   4.483752   11.7    19.60    22.8    26.0   
Rainfall       3271.0     3.342158   9.917746    0.0     0.00     0.0     1.4   
Evaporation    3271.0     5.175787   2.757684    0.0     3.20     4.8     7.0   
Sunshine       3271.0     7.168970   3.815966    0.0     4.25     8.3    10.2   
WindGustSpeed  3271.0    41.476307  10.806951   17.0    35.00    41.0    44.0   
WindSpeed9am   3271.0    15.077041   7.043825    0.0    11.00    15.0    20.0   
WindSpeed3pm   3271.0    19.294405   7.453331    0.0    15.00    19.0    24.0   
Humidity9am    3271.0    68.243962  15.086127   19.0    58.00    69.0    80.0   
Humidity3pm    3271.0    54.698563  16.279241   10.0    44.00    56.0    64.0   
Pressure9am    3271.0  1018.334424   7.020090  986.7  1013.70  1018.6  1023.1   
Pressure3pm    3271.0  1016.003085   7.019915  989.8  1011.30  1016.3  1020.8   
Cloud9am       3271.0     4.318557   2.526923    0.0     2.00     5.0     7.0   
Cloud3pm       3271.0     4.176093   2.411274    0.0     2.00     4.0     7.0   
Temp9am        3271.0    17.821461   4.894316    6.4    13.80    18.2    21.7   
Temp3pm        3271.0    21.543656   4.297053   10.2    18.40    21.3    24.5   

                  max  
MinTemp          27.6  
MaxTemp          45.8  
Rainfall        119.4  
Evaporation      18.4  
Sunshine         13.6  
WindGustSpeed    96.0  
WindSpeed9am     54.0  
WindSpeed3pm     57.0  
Humidity9am     100.0  
Humidity3pm      99.0  
Pressure9am    1039.0  
Pressure3pm    1036.7  
Cloud9am          9.0  
Cloud3pm          8.0  
Temp9am          36.5  
Temp3pm          44.7

In [5]:
df_encoded = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

In [6]:
df_encoded.replace(['No', 'Yes'], [0,1], inplace=True)

In [7]:
df_encoded.drop('Date',axis=1,inplace=True)

In [9]:
df_encoded=df_encoded.astype(float)

In [10]:
df_encoded

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0        19.5     22.4      15.6          6.2       0.0           41.0   
1        19.5     25.6       6.0          3.4       2.7           41.0   
2        21.6     24.5       6.6          2.4       0.1           41.0   
3        20.2     22.8      18.8          2.2       0.0           41.0   
4        19.7     25.7      77.4          4.8       0.0           41.0   
...       ...      ...       ...          ...       ...            ...   
3266      8.6     19.6       0.0          2.0       7.8           37.0   
3267      9.3     19.2       0.0          2.0       9.2           30.0   
3268      9.4     17.7       0.0          2.4       2.7           24.0   
3269     10.1     19.3       0.0          1.4       9.3           43.0   
3270      7.6     19.3       0.0          3.4       9.4           35.0   

      WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  ...  \
0             17.0          20.0         92.0         84.0  ...   
1              9.0          13.0         83.0         73.0  ...   
2             17.0           2.0         88.0         86.0  ...   
3             22.0          20.0         83.0         90.0  ...   
4             11.0           6.0         88.0         74.0  ...   
...            ...           ...          ...          ...  ...   
3266          22.0          20.0         73.0         52.0  ...   
3267          20.0           7.0         78.0         53.0  ...   
3268          15.0          13.0         85.0         56.0  ...   
3269          17.0          19.0         56.0         35.0  ...   
3270          13.0          13.0         73.0         32.0  ...   

      WindDir3pm_NNW  WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  \
0                0.0            0.0           0.0            0.0   
1                0.0            0.0           0.0            0.0   
2                0.0            0.0           0.0            0.0   
3                0.0            0.0           0.0            0.0   
4                0.0            0.0           0.0            0.0   
...              ...            ...           ...            ...   
3266             0.0            0.0           0.0            0.0   
3267             0.0            0.0           0.0            0.0   
3268             0.0            0.0           0.0            0.0   
3269             0.0            0.0           0.0            0.0   
3270             0.0            0.0           0.0            0.0   

      WindDir3pm_SSE  WindDir3pm_SSW  WindDir3pm_SW  WindDir3pm_W  \
0                0.0             1.0            0.0           0.0   
1                0.0             0.0            0.0           0.0   
2                0.0             0.0            0.0           0.0   
3                0.0             0.0            0.0           0.0   
4                0.0             0.0            0.0           1.0   
...              ...             ...            ...           ...   
3266             1.0             0.0            0.0           0.0   
3267             0.0             0.0            0.0           0.0   
3268             0.0             0.0            0.0           0.0   
3269             0.0             0.0            0.0           1.0   
3270             0.0             0.0            0.0           1.0   

      WindDir3pm_WNW  WindDir3pm_WSW  
0                0.0             0.0  
1                0.0             0.0  
2                0.0             0.0  
3                0.0             0.0  
4                0.0             0.0  
...              ...             ...  
3266             0.0             0.0  
3267             0.0             0.0  
3268             0.0             0.0  
3269             0.0             0.0  
3270             0.0             0.0  

[3271 rows x 67 columns]

In [11]:
X = df_encoded.drop(columns='RainTomorrow', axis=1)
y = df_encoded['RainTomorrow']

In [16]:
y.value_counts()

0.0    2422
1.0     849
Name: RainTomorrow, dtype: int64

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=10)

### Linear Regression

In [38]:
LinearReg = LinearRegression()
LinearReg.fit(X_train, y_train)

LinearRegression()

In [39]:
predictions = LinearReg.predict(X_test)
predictions

array([ 1.31782532e-01,  2.76153564e-01,  9.78088379e-01,  2.87483215e-01,
        1.32377625e-01,  4.60464478e-01,  3.56773376e-01,  8.56460571e-01,
        6.75010681e-01,  3.82766724e-02,  4.82940674e-03,  2.81181335e-01,
        3.39042664e-01,  7.80868530e-02,  6.26449585e-02,  5.64521790e-01,
       -6.15615845e-02,  5.24208069e-01,  1.53785706e-01,  3.59672546e-01,
        6.05087280e-02,  9.03572083e-01,  4.67338562e-01,  2.03323364e-01,
       -7.10830688e-02,  3.83865356e-01,  5.36071777e-01, -2.28652954e-02,
        6.40052795e-01, -9.56726074e-02,  3.78089905e-01,  1.20277405e-01,
       -1.81350708e-02,  5.53970337e-02,  5.63514709e-01,  1.06302643e+00,
       -6.73675537e-03,  5.14488220e-01, -8.83865356e-02,  6.92062378e-02,
        2.44827271e-02,  8.71726990e-01,  2.44621277e-01,  3.94760132e-01,
        2.67494202e-01,  4.46762085e-01, -4.75540161e-02,  1.89407349e-01,
        7.76573181e-01,  1.57707214e-01,  3.91387939e-03, -5.19638062e-02,
        2.07328796e-01, -

In [40]:
# Calculate Mean Absolute Error (MAE)
LinearRegression_MAE = mean_absolute_error(y_test, predictions)

# Calculate Mean Squared Error (MSE)
LinearRegression_MSE = mean_squared_error(y_test, predictions)

# Calculate R-squared (R2)
LinearRegression_R2 = r2_score(y_test, predictions)

In [41]:
Report = pd.DataFrame({
    'Metric': ['Mean Absolute Error (MAE)', 'Mean Squared Error (MSE)', 'R-squared (R2)'],
    'Linear Regression Value': [LinearRegression_MAE, LinearRegression_MSE, LinearRegression_R2]
})

In [42]:
Report

Metric  Linear Regression Value
0  Mean Absolute Error (MAE)                 0.256319
1   Mean Squared Error (MSE)                 0.115723
2             R-squared (R2)                 0.427121

### KNN

In [43]:
KNN = KNeighborsClassifier()
KNN.fit(X_train, y_train)

KNeighborsClassifier()

In [44]:
predictions = KNN.predict(X_test)
predictions

array([0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1.

In [45]:
KNN_Accuracy_Score = accuracy_score(y_test, predictions)
KNN_JaccardIndex = jaccard_score(y_test, predictions)
KNN_F1_Score = f1_score(y_test, predictions)

In [46]:
# Create a DataFrame
report = pd.DataFrame({
    'Metric': ['Accuracy Score', 'Jaccard Index', 'F1 Score'],
    'KNN Value': [KNN_Accuracy_Score, KNN_JaccardIndex, KNN_F1_Score]
})

report

Metric  KNN Value
0  Accuracy Score   0.819847
1   Jaccard Index   0.466063
2        F1 Score   0.635802

### Decision Tree


In [47]:
Tree = DecisionTreeClassifier()
Tree.fit(X_train, y_train)

DecisionTreeClassifier()

In [48]:
predictions = Tree.predict(X_test)
predictions

array([0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1.

In [49]:
Tree_Accuracy_Score = accuracy_score(y_test, predictions)
Tree_JaccardIndex = jaccard_score(y_test, predictions)
Tree_F1_Score = f1_score(y_test, predictions)

In [50]:
# Create a DataFrame
report = pd.DataFrame({
    'Metric': ['Accuracy Score', 'Jaccard Index', 'F1 Score'],
    'Tree Value': [Tree_Accuracy_Score, Tree_JaccardIndex, Tree_F1_Score]
})

report

Metric  Tree Value
0  Accuracy Score    0.752672
1   Jaccard Index    0.397770
2        F1 Score    0.569149

### Logistic Regression

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1)

In [52]:
LR =LogisticRegression(solver='liblinear')
LR.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [53]:
predictions = LR.predict(X_test)
predictions

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 1., 0.

In [54]:
predict_proba = LR.predict_proba(X_test)
predict_proba

array([[0.74339483, 0.25660517],
       [0.97495683, 0.02504317],
       [0.50982014, 0.49017986],
       ...,
       [0.98010306, 0.01989694],
       [0.69834832, 0.30165168],
       [0.22120583, 0.77879417]])

In [55]:
# Calculate Accuracy Score
LR_Accuracy_Score = accuracy_score(y_test, predictions)

# Calculate Jaccard Index
LR_JaccardIndex = jaccard_score(y_test, predictions)

# Calculate F1 Score
LR_F1_Score = f1_score(y_test, predictions)

LR_Log_Loss = log_loss(y_test, predict_proba)

In [56]:
# Create a DataFrame
report = pd.DataFrame({
    'Metric': ['Accuracy Score', 'Jaccard Index', 'F1 Score', 'Log Loss'],
    'LR Value': [LR_Accuracy_Score, LR_JaccardIndex, LR_F1_Score, LR_Log_Loss]
})

report

Metric  LR Value
0  Accuracy Score  0.836641
1   Jaccard Index  0.509174
2        F1 Score  0.674772
3        Log Loss  0.381064

### SVM

In [59]:
SVM = SVC()
SVM.fit(X_train, y_train)

SVC()

In [60]:
predictions = SVM.predict(X_test)
predictions

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [61]:
# Calculate Accuracy Score
SVM_Accuracy_Score = accuracy_score(y_test, predictions)

# Calculate Jaccard Index
SVM_JaccardIndex = jaccard_score(y_test, predictions)

# Calculate F1 Score
SVM_F1_Score = f1_score(y_test, predictions)

In [62]:
# Create a DataFrame
Report = pd.DataFrame({
    'Metric': ['Accuracy Score', 'Jaccard Index', 'F1 Score'],
    'LR Value': [SVM_Accuracy_Score, SVM_JaccardIndex, SVM_F1_Score]
})

Report

Metric  LR Value
0  Accuracy Score  0.722137
1   Jaccard Index  0.000000
2        F1 Score  0.000000